[package]

name = "ox"
version = "0.0.1"
authors = ["okey <oscar.c.key@gmail.com>"]

include = ["Cargo.toml", "src/**/*.rs", "src/**/*.rustpeg"]

[dependencies]
peg = "0.3.14"
byteorder = "0.5.3"
docopt = "0.6.82"
docopt_macros = "0.6.85"
rustc-serialize = "0.3.19"
