[package]

name = "ox"
version = "0.0.1"
authors = ["okey <oscar.c.key@gmail.com>"]

include = ["Cargo.toml", "src/**/*.rs", "src/**/*.rustpeg"]

[dependencies]
peg = "*"
byteorder = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
